[Server] Add RN entry for broken logging of auth container
Also add regression test for correct logging format and remove duplicate millisecond from time format

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1051,6 +1051,13 @@ test_job_miro_server:
     - '[ "$[[ inputs.skip-tests ]]" = true ] && echo "Skipping tests" && exit 0'
     - '[[ "$CI_COMMIT_BRANCH" == "master" ]] && [ "$[[ inputs.run-tests-master ]]" = false ] && echo "Skipping tests on master" && exit 0'
     - ./scripts/test_miro_server.sh
+    - |
+      BAD_LOGS=$(grep "auth-1" miro_server_all_logs.txt | sed -E -n '/\[[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}\] [A-Z]+ - [a-zA-Z0-9_.]+ -/!p')
+      if [ -n "$BAD_LOGS" ]; then
+        echo "🚨 ERROR: Found auth-1 logs with incorrect formatting:"
+        echo "$BAD_LOGS"
+        exit 1
+      fi
   dependencies: []
   artifacts:
     when: always
