[ci skip] allow manual build trigger even if [ci skip] is set

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -22,12 +22,16 @@ pipeline {
             agent { label 'docker' }
             steps {
                 catchError {
-                    sh '''#!/bin/bash -xe
-                        if git log -1 | grep -qi '.*\\[ci skip\\].*'; then
-                            echo "Found [ci skip] in commit message. Aborting.";
-                            exit 1
-                        fi
-                    '''
+                    script {
+                        if ( !currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') ){
+                          sh '''#!/bin/bash -xe
+                              if git log -1 | grep -qi '.*\\[ci skip\\].*'; then
+                                  echo "Found [ci skip] in commit message. Aborting.";
+                                  exit 1
+                              fi
+                          '''
+                        }
+                    }
                 }
                 step([$class: 'WsCleanup'])
             }
